// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPYDjvJSJc_JetZ7BcA4QEe8JDFmOBTAU',
    appId: '1:758376005903:web:0f95693eed780a9f7ebe7a',
    messagingSenderId: '758376005903',
    projectId: 'student-opportunity-hub-44329',
    authDomain: 'student-opportunity-hub-44329.firebaseapp.com',
    storageBucket: 'student-opportunity-hub-44329.firebasestorage.app',
    measurementId: 'G-830QKD874J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpG4qpR10WM5q9dSOMrUvrT7S_GJFN2Fo',
    appId: '1:758376005903:android:a06932264b9be35a7ebe7a',
    messagingSenderId: '758376005903',
    projectId: 'student-opportunity-hub-44329',
    storageBucket: 'student-opportunity-hub-44329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuNpM9kTNylLyVQmqnn-TQZo974VPXkYE',
    appId: '1:758376005903:ios:e30403ab893456577ebe7a',
    messagingSenderId: '758376005903',
    projectId: 'student-opportunity-hub-44329',
    storageBucket: 'student-opportunity-hub-44329.firebasestorage.app',
    iosBundleId: 'com.example.studentOpportunityHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuNpM9kTNylLyVQmqnn-TQZo974VPXkYE',
    appId: '1:758376005903:ios:e30403ab893456577ebe7a',
    messagingSenderId: '758376005903',
    projectId: 'student-opportunity-hub-44329',
    storageBucket: 'student-opportunity-hub-44329.firebasestorage.app',
    iosBundleId: 'com.example.studentOpportunityHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPYDjvJSJc_JetZ7BcA4QEe8JDFmOBTAU',
    appId: '1:758376005903:web:356aa53407d766d47ebe7a',
    messagingSenderId: '758376005903',
    projectId: 'student-opportunity-hub-44329',
    authDomain: 'student-opportunity-hub-44329.firebaseapp.com',
    storageBucket: 'student-opportunity-hub-44329.firebasestorage.app',
    measurementId: 'G-1NKD741NMW',
  );
}
